import Footer from './Footer/page'
import Header from './Header/page'
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import commonStyle from './page.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: '家計簿アプリ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <div className={commonStyle.pageMain}>
            {children}
          </div>
        </Providers>
        <Footer />
      </body>
    </html>
  )
}
